using System;
using System.Runtime.InteropServices;
using CsInjection.Native;
using CsInjection.Utilities;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace CsInjection.Tests
{
    [TestClass]
    public class MemoryTests
    {
        [TestMethod]
        public void Write()
        {
            // Allocate memory
            IntPtr allocatedMemory = Marshal.AllocHGlobal(1024);

            // Get a random byte buffer
            byte[] rndBytes = new byte[1024];
            new Random().NextBytes(rndBytes);

            // Write the random byte buffer to the newly allocated memory.
            Memory.Write(allocatedMemory, rndBytes);

            // Check the byes written to the allocated memory if they are the same as the randomly generated bytes.
            byte[] memValue = Memory.Read<byte[]>(allocatedMemory, 1024);

            for (int i = 0; i < rndBytes.Length; i++)
            {
                // Validate if the bytes are equal.
                Assert.AreEqual(memValue[i], rndBytes[i]);
            }
        }

        [TestMethod]
        public void Read()
        {
        }

        [TestMethod]
        public void ReadStruct()
        {

        }

        struct Test
        {

        }
    }
}
